server config by hardope

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,91 +1,84 @@
-#!/usr/bin/env bash 
-# Script for transferring a file from our client to a server using SCP
-# Assigning parameters to variables
-# Check if correct number of arguments are provided
+#!/usr/bin/env bash
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-if [ "$#" -ne 4 ]; then
-    echo "Usage: $0 PATH_TO_FILE SERVER_IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
-fi
+# uncomment to see the script run in action
+#set -x
 
-file_path="$1"
-server_ip="$2"
-username="$3"
-ssh_key="$4"
+echo -e "Updating and doing some minor checks...\n"
 
-# Transfer file using SCP
-scp -o StrictHostKeyChecking=no -i "${ssh_key}" "${file_path}" "${username}@${server_ip}:~/"
+function install() {
+	command -v "$1" &> /dev/null
 
-# Configures Nginx server for redirection and default error pages
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
 
-# Update package lists
-sudo apt-get -y update
+install nginx #install nginx
 
-# Install nginx
-sudo apt-get -y install nginx
-
-# Create a backup of the default configuration file
-sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
+echo -e "\nSetting up some minor stuff.\n"
 
 # allowing nginx on firewall
 sudo ufw allow 'Nginx HTTP'
 
 # Give the user ownership to website files for easy editing
 if [ -d "/var/www" ]; then
-    sudo chown -R "$USER":"$USER" /var/www
-    sudo chmod -R 755 /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
 else
-    sudo mkdir -p /var/www
-    sudo chown -R "$USER":"$USER" /var/www
-    sudo chmod -R 755 /var/www
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
 fi
 
 # create directories if not present
 for dir in /var/www/{html,error}; do
-    if ! [ -d "$dir" ]; then
-        sudo mkdir -p "$dir"
-    fi
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
 done
 
-# Echo "Hello World!" to the default index file
-echo "Hello World!" | sudo tee "/var/www/html/index.nginx-debian.html"
-
-# Define website directory
-WEBSITE_DIR="/var/www/html"
-
-# Restore default configuration for a 301 redirect
-sudo sed -i '/server_name _;/a\    location = \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
 
 # create new error page
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-# Restore default error page configurations
-sudo sed -i '/error_page 404/c\    error_page 404 /404.html;' /etc/nginx/sites-available/default
-sudo sed -i '/location \= \/404.html/c\    location = \/404.html {\n        root \/usr\/share\/nginx\/html;\n        internal;\n    }' /etc/nginx/sites-available/default
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-# Define server configuration
-SERVER_CONFIG="server {
-    listen 80 default_server;
-    listen [::]:80 default_server;
-    root $WEBSITE_DIR;
-    index index.html index.htm index.nginx-debian.html;
-    server_name _;
-    add_header X-Served-By \$hostname;
-    location / {
-        try_files \$uri \$uri/ =404;
-    }
-    location = /redirect_me {
-        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
-    }
-    error_page 404 /404.html;
-    location = /404.html {
-        internal;
-    }
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
 }"
 
-# Append server configuration to Nginx configuration file
-echo "$SERVER_CONFIG" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
 
-# Restart Nginx service to apply changes
-sudo service nginx restart
-
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
